# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b603370ac8260197608bbe112f7ba2664a9b81f6cf975efbe38b3db021c5dda24740739f5171a5e0f90db66ba73e5a88c986b3c02c9d7cd5a1b4974d9940a369

test:
  secret_key_base: 2f678b466b03dcaab6614d6f9e2f712769f95d261e6036eae7e9afe30ef2a3b5581e0326b9fc05143262586203dfa973b3e165a99e587d91af6ae48ae7bffe07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
